 workflows:
  default-workflow:
    name: Default Workflow 
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
        - pattern: excluded-target
          include: false
          source: false
        - pattern: included-source
          include: true
          source: true
      tag_patterns: # Include or exlude watched tag labels
        - pattern: '*'
          include: true
        - pattern: excluded-tag
          include: false
        - pattern: included-tag
          include: true
      cancel_previous_builds: false  # Set to `true` to automatically cancel outdated webhook builds
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - arjungoel1995@gmail.com